baseurl = "https://stephdesilva.com/"
languageCode = "en-us"
title = "Steph de Silva"
theme = "hugo-strata-theme"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Steph de Silva"
	description = "Data Science and Analytics"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add read time estimates in the format "X min read"
	show_read_time = false

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "avatar.png"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "Steph de Silva, Ph.D."
		# The icons will be shown if you enter your username
		twitter = "@stephdesilva"
		github = "stephdesilva"
		linkedin = "steph-de-silva-93b18444"

		copyright = [
			"&copy; Steph de SIlva",
			"Design: [HTML5 UP](//html5up.net)"
		]


	[params.about]
		hide  = false
		title = "Bio"
		content = "Steph de Silva is a Ph.D. data scientist. She currently works in management consulting. Previously, she spent four years with the World Bank before going on to found her own boutique data scicence consultancy <a href="https://www.rex-analytics.com">Rex Analytics</a>."


	[params.portfolio]
		hide  = false
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "nautilus1.jpg"
			thumb = "nautilus1.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "spiral_log.jpg"
			thumb = "spiral_log.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "raspberry_pi.jpg"
			thumb = "raspberry_pi.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "rock.jpg"
			thumb = "rock.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "spiral_log.jpg"
			thumb = "spiral_log.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "urchin.jpg"
			thumb = "urchin.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = false
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		# This can be exact coordinates or a searchable address in google maps
		gmaps_address = "39.7889055,-120.5443524"
		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "steph@rex-analytics.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar
[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 10

[[menu.main]]
	name = "Blog"
	url  = "post/"
	weight = 0
	
[[menu.main]]
	name = "CV"
	url  = "cv/"
	weight = 0

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]